### ISSUE TITLE
인터넷의 이해

### ISSUE THREAD

**Issue by daeseokyoun** [oss-devel-begin/issue-tracker-note#9]
## Khan 아카데미
 - [인터넷](https://ko.khanacademy.org/computing/computer-science/internet-intro)의 이해
 - 꼭 보기

**Comment by gusdlf93** [comment]
와우... 이건 근래 들은 강의들 중에서도 최고네요 
감사합니다.

**Comment by daeseokyoun** [comment]
@gusdlf93 @kjh1007 그런 이해를 쉽게하기 위한 강의들도 찾으면 공유드리겠습니다.
